// <auto-generated />
using System;
using Klir.TechChallenge.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Klir.TechChallenge.Infrastructure.Migrations
{
    [DbContext(typeof(ForecastContext))]
    [Migration("20180729185706_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Klir.TechChallenge.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateForecast")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TemperatureC");

                    b.Property<int>("TemperatureF");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecast");

                    b.HasData(
                        new { Id = 1, DateForecast = new DateTime(2018, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Scorching", TemperatureC = 32, TemperatureF = 89 },
                        new { Id = 2, DateForecast = new DateTime(2018, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Mild", TemperatureC = 45, TemperatureF = 112 },
                        new { Id = 3, DateForecast = new DateTime(2018, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Mild", TemperatureC = -4, TemperatureF = 25 },
                        new { Id = 4, DateForecast = new DateTime(2018, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Balmy", TemperatureC = 16, TemperatureF = 60 },
                        new { Id = 5, DateForecast = new DateTime(2018, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), Summary = "Hot", TemperatureC = 53, TemperatureF = 127 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
